#ifndef COMPONENT_IDS_H
#define COMPONENT_IDS_H

#define GPS_LATITUDE_ID 1
#define GPS_LONGITUDE_ID 2
#define MOTOR_POWER_WATTS_ID 3
#define BATTERY_LEVEL_ID 4
#define MOTOR_TEMPERATURE_ID 5
#define BATTERY_VOLTAGE_ID 6


#define MOTOR_POWER_PERCENT_ID 50
#define RUDDER_ANGLE_ID 51

#endif